"""Add platform, sentiment, keywords to posts

Revision ID: a7194e1062ae
Revises: 
Create Date: 2025-09-22 23:24:08.392631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7194e1062ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('platform', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('sentiment', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('keywords', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'keywords')
    op.drop_column('posts', 'sentiment')
    op.drop_column('posts', 'platform')
    # ### end Alembic commands ###
